pipeline {
    agent any

    environment {
        IMAGE_NAME = "yourdockerhub/devopsecom"
        IMAGE_TAG  = "${BUILD_NUMBER}"
        GITOPS_REPO = "https://github.com/yourname/devops-gitops-repo.git"
    }

    stages {

        stage('Checkout App Repo') {
            steps {
                git branch: 'main',
                url: 'https://github.com/yourname/devops-app-repo.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $IMAGE_NAME:$IMAGE_TAG .'
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([string(credentialsId: 'dockerhub-pass', variable: 'PASS')]) {
                    sh '''
                    docker login -u yourdockerhub -p $PASS
                    docker push $IMAGE_NAME:$IMAGE_TAG
                    '''
                }
            }
        }

        stage('Clone GitOps Repo') {
            steps {
                sh 'git clone $GITOPS_REPO'
            }
        }

        stage('Update Deployment Manifest') {
            steps {
                sh '''
                sed -i "s|image:.*|image: $IMAGE_NAME:$IMAGE_TAG|" \
                devops-gitops-repo/k8s-manifests/deployment.yaml
                '''
            }
        }

        stage('Commit & Push GitOps Changes') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'github-creds',
                    usernameVariable: 'USER',
                    passwordVariable: 'PASS'
                )]) {
                    sh '''
                    cd devops-gitops-repo
                    git config user.name "jenkins"
                    git config user.email "jenkins@ci.com"
                    git add .
                    git commit -m "Updated image to $IMAGE_TAG"
                    git push https://$USER:$PASS@github.com/yourname/devops-gitops-repo.git main
                    '''
                }
            }
        }
    }
}
