pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "yourdockerhub/devops-app"
        IMAGE_TAG    = "${BUILD_NUMBER}"
    }

    triggers {
        githubPush()
    }

    stages {

        stage('Build Docker Image') {
            steps {
                dir('devops-app-repo') {
                    sh "docker build -t ${DOCKER_IMAGE}:${IMAGE_TAG} ."
                }
            }
        }

        stage('Push Image') {
            steps {
                withCredentials([string(credentialsId: 'dockerhub-pass', variable: 'PASS')]) {
                    sh """
                    echo \$PASS | docker login -u yourdockerhub --password-stdin
                    docker push ${DOCKER_IMAGE}:${IMAGE_TAG}
                    """
                }
            }
        }

        stage('Update GitOps Repo') {
            steps {
                withCredentials([string(credentialsId: 'github-pat', variable: 'GITHUB_TOKEN')]) {
                    dir('devops-gitops-repo') {
                        sh """
                        git remote set-url origin https://${GITHUB_TOKEN}@github.com/chakri8991/devopsecom1.git
                        sed -i 's|IMAGE_TAG|${IMAGE_TAG}|g' k8s-manifests/deployment.yaml
                        git config user.name "jenkins"
                        git config user.email "jenkins@devops.com"
                        git add .
                        git commit -m "Update image to ${IMAGE_TAG}" || echo "No changes"
                        git push origin main
                        """
                    }
                }
            }
        }
    }
}


