pipeline {
    agent any

    environment {
        IMAGE_NAME = "yourdockerhub/devops-app"
        IMAGE_TAG = "${BUILD_NUMBER}"
        GIT_CREDENTIALS = "github-creds"
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main',
                url: 'https://github.com/yourname/devops-project.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                docker build -t $IMAGE_NAME:$IMAGE_TAG .
                '''
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([string(credentialsId: 'dockerhub-pass', variable: 'PASS')]) {
                    sh '''
                    docker login -u yourdockerhub -p $PASS
                    docker push $IMAGE_NAME:$IMAGE_TAG
                    '''
                }
            }
        }

        stage('Update Kubernetes Manifest') {
            steps {
                sh '''
                sed -i "s|image:.*|image: $IMAGE_NAME:$IMAGE_TAG|" k8s-manifests/deployment.yaml
                '''
            }
        }

        stage('Commit Manifest Changes') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'github-creds',
                    usernameVariable: 'USER',
                    passwordVariable: 'PASS'
                )]) {
                    sh '''
                    git config user.email "jenkins@ci.com"
                    git config user.name "jenkins"
                    git add k8s-manifests/deployment.yaml
                    git commit -m "Updated image to $IMAGE_TAG"
                    git push https://$USER:$PASS@github.com/yourname/devops-project.git main
                    '''
                }
            }
        }
    }
}
